### ISSUE TITLE
Use Type/default for template variables?

### ISSUE THREAD

**Issue by jsoo1** [weeezes/dhall-grafana#27]
I would like to use something like `TemplateVariable.CustomVariable::{ description ... }` for template variables but the current smart constructors don't quite allow this. I think this would be a breaking change, so I wanted to know what you thought of the idea.

**Comment by weeezes** [comment]
I think this would be a very reasonable change, as I'm not even sure myself why I went with this current path anymore 😅. Might have been just a bit too eager when starting to learn Dhall, oops!

What could be done is that we still export the smart constructors, but also export proper records with default values. The smart constructors could be changed to use these default records instead, thus making it non-breaking I believe? What do you think?

**Comment by jsoo1** [comment]
That seems like a reasonable idea to me :)

**Comment by weeezes** [comment]
Taking a stab at this now

**Comment by weeezes** [comment]
Was simpler than I thought https://github.com/weeezes/dhall-grafana/pull/30 :)

**Comment by jsoo1** [comment]
Excellent! Thank you so much!
